### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by monperrus** [KevinGoodsell/mork-converter#1]
running `python mork INBOX.msf` gives an exception:

```
Generating LALR tables
Syntax error at token LexToken(!,'!',370864,22013860)
Syntax error at token LexToken(!,'!',385398,22488077)
Traceback (most recent call last):
  File "mork", line 147, in <module>
    sys.exit(main())
  File "mork", line 140, in main
    process_database(f, filters, opts)
  File "mork", line 86, in process_database
    db = morkdb.MorkDatabase.from_ast(tree)
  File "/tmp/mork-converter/src/MorkDB/morkdb.py", line 354, in from_ast
    self.build_item(item)
  File "/tmp/mork-converter/src/MorkDB/morkdb.py", line 345, in build_item
    builder(ast, self)
  File "/tmp/mork-converter/src/MorkDB/morkdb.py", line 232, in process_mork_group_ast
    db.build_item(item)
  File "/tmp/mork-converter/src/MorkDB/morkdb.py", line 345, in build_item
    builder(ast, self)
  File "/tmp/mork-converter/src/MorkDB/morkdb.py", line 135, in from_ast
    db._readRows(ast.rows, namespace, self)
  File "/tmp/mork-converter/src/MorkDB/morkdb.py", line 324, in _readRows
    self.rows[row_namespace, rowid])
KeyError: ('ns:msg:db:row:scope:msgs:all', '15')
```

**Comment by KevinGoodsell** [comment]
I'm not sure the exception is meaningful following a systax error. Is it possible to send me the file for diagnosis?

**Comment by monperrus** [comment]
The Mozilla Thunderbird MSF file contains too much private information
(email, sender, subject) and I'm unable to reproduce the bug on a
smaller file. I guess you can close the bug.

Thanks, --Martin

**Comment by KevinGoodsell** [comment]
It's a bit more work, but what if you ran with the --tokens option and captured the output into a file? Then you could search that file for LexTokens containing '!'. If you can find the two corresponding to the two syntax errors, then you could send snippets of the 10 lines before & after those tokens, which likely won't contain anything sensitive, and you can examine it to verify that (and you can edit any strings that you aren't comfortable sending).

As far as I can tell, the ! token is only used to indicate a row move operation, so it's probably not directly related to the size of the file, but more to the operations that have been performed on it.

I take it this was from Thunderbird, then? Do you know the Thunderbird version? I may be able to get some insight by looking at how ! is parsed in there.

**Comment by monperrus** [comment]
Hi Kevin,

Hope this helps:

```
Syntax error at token LexToken(!,'!',370864,22013860)
Syntax error at token LexToken(!,'!',385398,22488077)
Traceback (most recent call last):
  File "mork", line 147, in <module>
    sys.exit(main())
  File "mork", line 140, in main
    process_database(f, filters, opts)
  File "mork", line 86, in process_database
    db = morkdb.MorkDatabase.from_ast(tree)
  File "/tmp/mork-converter/src/MorkDB/morkdb.py", line 354, in from_ast
    self.build_item(item)
  File "/tmp/mork-converter/src/MorkDB/morkdb.py", line 345, in build_item
    builder(ast, self)
  File "/tmp/mork-converter/src/MorkDB/morkdb.py", line 232, in process_mork_group_ast
    db.build_item(item)
  File "/tmp/mork-converter/src/MorkDB/morkdb.py", line 345, in build_item
    builder(ast, self)
  File "/tmp/mork-converter/src/MorkDB/morkdb.py", line 135, in from_ast
    db._readRows(ast.rows, namespace, self)
  File "/tmp/mork-converter/src/MorkDB/morkdb.py", line 324, in _readRows
    self.rows[row_namespace, rowid])
KeyError: ('ns:msg:db:row:scope:msgs:all', '15')

LexToken(HEX,'BE',370864,22013844)
LexToken(VALUE,'',370864,22013846)
LexToken(RPAREN,')',370864,22013847)
LexToken(LPAREN,'(',370864,22013848)
LexToken(CARET,'^',370864,22013849)
LexToken(HEX,'E0',370864,22013850)
LexToken(CARET,'^',370864,22013852)
LexToken(HEX,'3E3E4',370864,22013853)
LexToken(RPAREN,')',370864,22013858)
LexToken(],']',370864,22013859)
LexToken(!,'!',370864,22013860)
LexToken(HEX,'15',370864,22013861)
LexToken(},'}',370864,22013864)
LexToken({,'{',370865,22013866)
LexToken(-,'-',370865,22013867)
LexToken(HEX,'F03A',370865,22013868)
LexToken(COLON,':',370865,22013872)
LexToken(CARET,'^',370865,22013873)
LexToken(HEX,'80',370865,22013874)
LexToken({,'{',370865,22013877)
LexToken(LPAREN,'(',370865,22013878)


LexToken(HEX,'C9',385398,22488060)
LexToken(CARET,'^',385398,22488062)
LexToken(HEX,'3F15B',385398,22488063)
LexToken(RPAREN,')',385398,22488068)
LexToken(LPAREN,'(',385398,22488069)
LexToken(CARET,'^',385398,22488070)
LexToken(HEX,'CC',385398,22488071)
LexToken(VALUE,'1',385398,22488073)
LexToken(RPAREN,')',385398,22488075)
LexToken(],']',385398,22488076)
LexToken(!,'!',385398,22488077)
LexToken(HEX,'E',385398,22488078)
LexToken(},'}',385398,22488080)
LexToken({,'{',385399,22488082)
LexToken(-,'-',385399,22488083)
LexToken(HEX,'EF4F',385399,22488084)
LexToken(COLON,':',385399,22488088)
LexToken(CARET,'^',385399,22488089)
LexToken(HEX,'80',385399,22488090)
LexToken({,'{',385399,22488093)
LexToken(LPAREN,'(',385399,22488094)
```

**Comment by monperrus** [comment]
> I take it this was from Thunderbird, then? Do you know the Thunderbird
> version?
> I use Thunderbird version 38 (the latest beta).

**Comment by KevinGoodsell** [comment]
I'm not too sure what's happening yet (I need to refresh my memory on some of the details), but I noticed this comment in the documentation I wrote about Mork:

> Based on ReadRow in morkParser.cpp[2](the first call to ReadRowPos), it
> appears that a row move operation can also appear after a row object,
> combining the row add/update and row move operations. In practice this
> might not be used.

It looks like this may be a case where it _is_ used in practice, and I don't think my parser handles this case.
