### ISSUE TITLE
ImportError: No module named ply.yacc

### ISSUE THREAD

**Issue by ajmas** [KevinGoodsell/mork-converter#2]
I am getting the following error when trying to run with Python 2.7.10:

```
Traceback (most recent call last):
  File "./mork", line 147, in <module>
    sys.exit(main())
  File "./mork", line 140, in main
    process_database(f, filters, opts)
  File "./mork", line 83, in process_database
    import MorkDB.morkyacc as morkyacc
  File "/Users/MyUser/Development/third-party/mork-converter/src/MorkDB/morkyacc.py", line 29, in <module>
    import ply.yacc as yacc
ImportError: No module named ply.yacc
```

What should I do to resolve?

**Comment by ajmas** [comment]
Missed I needed ply installed. Installed and now it works

**Comment by lawrence-l20** [comment]
Still does not work! I installed Ply and still get the error! How do I solve this?

**Comment by ajmas** [comment]
How did you install ply? Also what version of Python are you using?
